package com.done.model;

import java.util.Date;

/**
 * News generated by MyEclipse Persistence Tools
 */

public class News implements java.io.Serializable {

    // Fields

    private Integer newsId;

    private String newsTitle;

    private String newsContent;

    private Date newsDate;
    /**
     * 1:上线 0：下线
     */
    private Integer status;

    private String userId;

    private String userName;

    // Constructors

    /** default constructor */
    public News() {
    }

    /** minimal constructor */
    public News(Integer newsId) {
        this.newsId = newsId;
    }

    /** full constructor */
    public News(Integer newsId, String newsTitle, String newsContent, Date newsDate, Integer status, String userId,
            String userName) {
        this.newsId = newsId;
        this.newsTitle = newsTitle;
        this.newsContent = newsContent;
        this.newsDate = newsDate;
        this.status = status;
        this.userId = userId;
        this.userName = userName;
    }

    // Property accessors

    public Integer getNewsId() {
        return this.newsId;
    }

    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    public String getNewsTitle() {
        return this.newsTitle;
    }

    public void setNewsTitle(String newsTitle) {
        this.newsTitle = newsTitle;
    }

    public String getNewsContent() {
        return this.newsContent;
    }

    public void setNewsContent(String newsContent) {
        this.newsContent = newsContent;
    }

    public Date getNewsDate() {
        return this.newsDate;
    }

    public void setNewsDate(Date newsDate) {
        this.newsDate = newsDate;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

}